cmd = 'python cli.py -b {backend} -l "{uid}" -s {seed} -t {float} train -n {num_steps} -d {dataset} -o {opt}'

[[exp]]
cmd = '{cmd} cglb -k {kernel} -m {model} -i ConditionalVariance -M {num_ips} --{voption}'
uid = './{rootdir}/camera/{dataset}/{model}-{kernel}-{num_ips}-{float}-{opt}-{voption}/{seed}'

backend = "tf"
float = "fp64"
rootdir = "logs"
num_steps = 2000
kernel = "Matern32"
opt = "scipy"
model = "cglb"
voption = ["vzero", "vjoint"]
seed = [1111, 999, 888, 777, 666]
dataset = ["Wilson_pol", "Wilson_bike", "Wilson_elevators"]
num_ips = [1024, 2048, 4096]


[[exp]]
cmd = '{cmd} cglb -k {kernel} -m {model} -i ConditionalVariance -M {num_ips}'
uid = './{rootdir}/camera/{dataset}/{model}-{kernel}-{num_ips}-{float}-{opt}/{seed}'

backend = "tf"
float = "fp64"
rootdir = "logs"
num_steps = 2000
kernel = "Matern32"
opt = "scipy"
model = "cglbn2m"
seed = [1111, 999, 888, 777, 666]
dataset = ["Wilson_pol", "Wilson_bike", "Wilson_elevators"]
num_ips = [1024, 2048, 4096]

[[exp]]
cmd = '{cmd} sgpr -k {kernel} -m {model} -i ConditionalVariance -M {num_ips}'
uid = './{rootdir}/camera/{dataset}/{model}-{kernel}-{num_ips}-{float}-{opt}/{seed}'

backend = "tf"
float = "fp64"
rootdir = "logs"
num_steps = 2000
kernel = "Matern32"
opt = "scipy"
model = "sgprn2m"
seed = [1111, 999, 888, 777, 666]
dataset = ["Wilson_pol", "Wilson_bike", "Wilson_elevators"]
num_ips = [1024, 2048, 4096]

[flags]
restart = false
# num_proc = 1
# gpu_indices = ["0"]
num_proc = 4
gpu_indices = ["0", "1", "2", "3"]
